### ISSUE TITLE
Kick kicks all players

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#111]
I think this is related to #106, but I am not sure. This is something it has been doing since at least when i started with build 59.

Kicks everyone, including the Op/admin who ran the command... LOL

**Comment by benbaptist** [comment]
Anything in the console? Does it kick all players with that reason, or just an error? What other info can you find?

**Comment by benbaptist** [comment]
I think I fixed it in the latest dev build. It wasn't even showing them as logging out. I wasn't able to reproduce the kick, but I definitely got some strange behaviour.

**Comment by suresttexas00** [comment]
that makes sense.. I heard people complain they were still seeing logged out people a being on-line

**Comment by suresttexas00** [comment]
Works great.  I sucessfully kicked from in-game and via web mode!
